### PR TITLE
Fix SO2 rotate and unrotate jacobian

### PR DESCRIPTION
**Pull request by fantaosha**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fantaosha** [comment]
Fixed a bug for the Jacobian matrices of `SO2.rotate()` and `SO2.unrotate()` when `SO2.shape[0] != Point2.shape[0]`

**Review by luisenp — APPROVED** [review]
LGTM. Did you also test the tactile pushing example just to be extra safe? After that and fix CI issues, merge looks OK to me.

**Review by mhmukadam — APPROVED** [review]

**Comment by fantaosha** [comment]
> LGTM. Did you also test the tactile pushing example just to be extra safe? After that and fix CI issues, merge looks OK to me.

The tactile pushing examples are passed. But since there are similar bugs in `SE2.transform()`, I would like to wait until everything is fixed.

**Review by luisenp — APPROVED** [review]
LGTM!

**Pull request merged**
