### PR TITLE
Allow vmap to work on th.SE3 log_map

### PR DESCRIPTION
**Pull request by rmurai0610**
## Motivation and Context
Replace `torch.zeros` with `new_zeros` to make log_map vmappable.
This is already fixed in the new api, but it wasn't in the old ones.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by fantaosha** [comment]
BTW, have you tested the compatibility of new Lie group lib for `vmap`? Does it support custom backward functions? Maybe @luisenp also knows the answer.

**Review by mhmukadam — APPROVED** [review]
LGTM! Thanks for the fix. Cuda wheel CI is failing but seems unrelated to the change here.

**Comment by luisenp** [comment]
LGTM. Thanks for the fix! Re-running CI, I think it was just a hiccup. Feel free to merge if CI passes.

**Comment by luisenp** [comment]
> BTW, have you tested the compatibility of new Lie group lib for `vmap`? Does it support custom backward functions? Maybe @luisenp also knows the answer.

My understanding is that custom backward won't work with `functorch` for versions before PyTorch 2.0, and then we might need to adjust some things for the upgrade.

**Pull request merged**
