### PR TITLE
Update continuous integration (torch 1.13, cuda 10 dropped)

### PR DESCRIPTION
**Pull request by maurimo**
## Motivation and Context

Since torch-1.13 is now used in a fundamental way (functorch), this diff upgrades the ci to use torch-1.13.
Support for Cuda 10.2 is dropped, and the reference Cuda 11 version is upgraded to 11.7 from 11.3 (as recommended by torch too).

## How Has This Been Tested

Ci itself should now succeed.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mhmukadam — APPROVED** [review]

**Comment by maurimo** [comment]
@mhmukadam @luisenp @fantaosha thank you for the approval, but not merging yet maybe? as in the chat we discussed that FAIR cluster only has CUDA 11.4 so perhaps it's best to stick with the previous setup and just lock the version of functorch so it doesn't trigger update of torch to 1.13.

**Comment by maurimo** [comment]
I propose to modify the CI (in another PR) so that functorch in installed together with torch, so we can make sure nothing goes wrong there and it's all in one place.

**Comment by mhmukadam** [comment]
Okay so we can close this PR? Or should we make it a draft and revive it when we are ready to upgrade the versions.

**Comment by luisenp** [comment]
Let's wait until I write the other PR, I think this one will be superseded by that one. Then we can close.

**Pull request closed without merging**
